---

- name: Install additional packages
  apt: name={{item}} state=present
  with_items:
   - mysql-server
   - mysql-client
   - php5
   - libapache2-mod-php5
   - php5-mysql
   - php5-cli
   - php5-common
   - libtext-csv-xs-perl
   
- name: Download NConf binaries
  command: wget http://sourceforge.net/projects/nconf/files/nconf/1.3.0-0/nconf-1.3.0-0.tgz/download -O /usr/share/nconf-1.3.0-0.tgz

- name: Unpack NConf binaries
  command: chdir=/usr/share tar xzvf nconf-1.3.0-0.tgz -C /var/www/html
  
- name: Set proper NConf directory permissions
  command: chdir=/var/www/html/nconf chmod 644 config output static_cfg temp
  
- name: Copy NConf DB script
  template: src=create-nconf-db.sql dest=/usr/share

- name: Create NConf DB
  shell: chdir=/usr/bin mysql -u "{{ DB_USER }}" --password= < /usr/share/create-nconf-db.sql

- name: Set NConf directory ownership
  file: path=/var/www/html/nconf owner=www-data group=www-data recurse=yes

- name: Set NConf directory permissions
  file: path=/var/www/html/nconf mode=0777

- name: Stop apache
  command: service apache2 stop
  
- name: Start apache
  command: service apache2 start